/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\Card.glb -T -t -s -o src\components\shared-3d\models\Card.tsx 
Files: public\Card.glb [2.14MB] > D:\FREELANCING\MAGIC TEAL\JUImain\src\components\shared-3d\models\Card-transformed.glb [118.7KB] (94%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
type GLTFAction = any

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh
  }
  materials: {
    WF: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model({ isMobile, ...props }: React.JSX.IntrinsicElements['group'] & { isMobile?: boolean }) {
  const { nodes, materials } = useGLTF('/models/Card-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Plane.geometry} material={materials.WF} />
    </group>
  )
}

useGLTF.preload('/models/Card-transformed.glb')

