/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/AnimatedModels/Card.glb --transform --types --shadows --keepnames --output src/components/shared-3d/models/Card.tsx 
Files: public/AnimatedModels/Card.glb [3.2MB] > D:\FREELANCING\MAGIC TEAL\JUImain\src\components\shared-3d\models\Card-transformed.glb [288.24KB] (91%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'
import { MotionValue } from 'framer-motion'

type ActionName = 'EmptyAction' | 'BottomAction' | 'Cube.002Action' | 'TopAction'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Plane009: THREE.Mesh
    Plane009_1: THREE.Mesh
    Cube004: THREE.Mesh
    Cube004_1: THREE.Mesh
    Plane005: THREE.Mesh
    Plane005_1: THREE.Mesh
  }
  materials: {
    ['Black ']: THREE.MeshPhysicalMaterial
    WF: THREE.MeshStandardMaterial
    Yellow: THREE.MeshPhysicalMaterial
    ['WF.02']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model({ progress, ...props }: React.JSX.IntrinsicElements['group'] & { isMobile?: boolean, progress?: MotionValue<number> }) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/AnimatedModels/Card-transformed.glb') as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)

  // Initialize animations but keep them paused
  React.useEffect(() => {
    Object.values(actions).forEach((action) => {
      if (action) {
        action.play().paused = true
      }
    })
  }, [actions])

  // Sync animation time with scroll progress
  useFrame(() => {
    if (progress) {
      const p = progress.get()
      Object.values(actions).forEach((action) => {
        if (action) {
          const duration = action.getClip().duration
          action.time = p * duration
        }
      })
    }
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty">
          <group name="Bottom" rotation={[0, 0, Math.PI]} scale={0.996}>
            <mesh name="Plane009" castShadow receiveShadow geometry={nodes.Plane009.geometry} material={materials['Black ']} />
            <mesh name="Plane009_1" castShadow receiveShadow geometry={nodes.Plane009_1.geometry} material={materials.WF} />
          </group>
          <group name="Cube002" position={[-0.831, 0, 0]}>
            <mesh name="Cube004" castShadow receiveShadow geometry={nodes.Cube004.geometry} material={materials.Yellow} />
            <mesh name="Cube004_1" castShadow receiveShadow geometry={nodes.Cube004_1.geometry} material={materials['WF.02']} />
          </group>
          <group name="Top" position={[-0.001, 0, 0]}>
            <mesh name="Plane005" castShadow receiveShadow geometry={nodes.Plane005.geometry} material={materials.WF} />
            <mesh name="Plane005_1" castShadow receiveShadow geometry={nodes.Plane005_1.geometry} material={materials['Black ']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/AnimatedModels/Card-transformed.glb')
