/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Model: /public/models/Coin_minting.glb
*/

'use client';

import * as THREE from 'three';
import React, { useMemo } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

// Ensure Draco decoder is configured before loading
useGLTF.setDecoderPath('https://www.gstatic.com/draco/v1/decoders/');

type GLTFResult = GLTF & {
  nodes: {
    Cylinder012: THREE.Mesh;
    Cylinder012_1: THREE.Mesh;
    Cylinder014: THREE.Mesh;
    Cylinder014_1: THREE.Mesh;
    Cylinder014_2: THREE.Mesh;
    Cylinder015: THREE.Mesh;
    Cylinder015_1: THREE.Mesh;
    Cylinder015_2: THREE.Mesh;
  };
  materials: {
    Black: THREE.MeshPhysicalMaterial;
    Wireframe: THREE.MeshStandardMaterial;
    Rupees_symbol: THREE.MeshStandardMaterial;
  };
};

export function CoinMinting(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Coin_minting.glb') as unknown as GLTFResult;

  // Enhance material properties for high-contrast neon cyan wireframe & vivid rupee emblems
  useMemo(() => {
    if (materials.Wireframe) {
      materials.Wireframe.emissive = new THREE.Color('#00ffff');
      materials.Wireframe.emissiveIntensity = 1.6;
      materials.Wireframe.toneMapped = false;
    }
    if (materials.Rupees_symbol) {
      materials.Rupees_symbol.emissive = new THREE.Color('#38bdf8');
      materials.Rupees_symbol.emissiveIntensity = 1.2;
      materials.Rupees_symbol.toneMapped = false;
      materials.Rupees_symbol.side = THREE.DoubleSide;
    }
    if (materials.Black) {
      materials.Black.roughness = 0.2;
      materials.Black.metalness = 0.1;
      materials.Black.transmission = 0.7;
      materials.Black.transparent = true;
      materials.Black.opacity = 0.85;
    }
  }, [materials]);

  return (
    <group {...props} dispose={null}>
      {/* Floating central coin rim */}
      <group position={[0, 0.001, 0]}>
        <mesh geometry={nodes.Cylinder012.geometry} material={materials.Black} />
        <mesh geometry={nodes.Cylinder012_1.geometry} material={materials.Wireframe} />
      </group>

      {/* Top die with Rupee insignia */}
      <group position={[0, 1.024, 0]}>
        <mesh geometry={nodes.Cylinder014.geometry} material={materials.Black} />
        <mesh geometry={nodes.Cylinder014_1.geometry} material={materials.Rupees_symbol} />
        <mesh geometry={nodes.Cylinder014_2.geometry} material={materials.Wireframe} />
      </group>

      {/* Bottom die with Rupee insignia */}
      <group position={[0, -1.023, 0]}>
        <mesh geometry={nodes.Cylinder015.geometry} material={materials.Black} />
        <mesh geometry={nodes.Cylinder015_1.geometry} material={materials.Rupees_symbol} />
        <mesh geometry={nodes.Cylinder015_2.geometry} material={materials.Wireframe} />
      </group>
    </group>
  );
}

export default CoinMinting;

useGLTF.preload('/models/Coin_minting.glb');
