/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/AnimatedModels/Earth1_locations.glb -o src/components/shared-3d/models/Earth1Locations.tsx -t -k -K -b -r /AnimatedModels 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    EARTHLayer2_NUAGES_0: THREE.Mesh
    Locations: THREE.Mesh
  }
  materials: {
    NUAGES: THREE.MeshStandardMaterial
    TERRE: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/AnimatedModels/Earth1_locations.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh name="EARTHLayer2_NUAGES_0" geometry={nodes.EARTHLayer2_NUAGES_0.geometry} material={materials.NUAGES} rotation={[0.472, 1.261, -0.248]} scale={0.02} />
        <mesh name="Locations" geometry={nodes.Locations.geometry} material={materials.TERRE} rotation={[0.472, 1.261, -0.248]} scale={0.02} />
      </group>
    </group>
  )
}

useGLTF.preload('/AnimatedModels/Earth1_locations.glb')
