/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Earth1_.2.glb -o src/components/shared-3d/models/EarthNew.tsx -t -k -K -s --root /models 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    EARTHLayer1_interior_black: THREE.Mesh
    EARTHLayer1_TERRE_0001: THREE.Mesh
  }
  materials: {
    Black: THREE.MeshStandardMaterial
    TERRE: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Earth1_.2.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh name="EARTHLayer1_interior_black" castShadow receiveShadow geometry={nodes.EARTHLayer1_interior_black.geometry} material={materials.Black} rotation={[0.309, 1.256, -0.305]} scale={0.02} />
        <mesh name="EARTHLayer1_TERRE_0001" castShadow receiveShadow geometry={nodes.EARTHLayer1_TERRE_0001.geometry} material={materials.TERRE} rotation={[0.309, 1.256, -0.305]} scale={0.02} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Earth1_.2.glb')
