/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Emblem.glb -T -t --output src/components/shared-3d/models/Emblem.tsx 
Files: public/models/Emblem.glb [12.67MB] > D:\FREELANCING\MAGIC TEAL\JUImain\src\components\shared-3d\models\Emblem-transformed.glb [1.48MB] (88%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFAction = any

type GLTFResult = GLTF & {
  nodes: {
    Cylinder002: THREE.Mesh
    Cylinder003: THREE.Mesh
    Cylinder004: THREE.Mesh
  }
  materials: {
    Black: THREE.MeshPhysicalMaterial
    Blue: THREE.MeshStandardMaterial
    Base: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Emblem-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.Black} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials.Blue} scale={0.787} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials.Base} position={[0, 0.002, 0]} scale={1.005} />
    </group>
  )
}

useGLTF.preload('/models/Emblem-transformed.glb')
