/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Emblem.glb --transform --types --output src/components/shared-3d/models/Emblem.tsx 
Files: public/models/Emblem.glb [723.08KB] > D:\FREELANCING\MAGIC TEAL\JUImain\src\components\shared-3d\models\Emblem-transformed.glb [231.62KB] (68%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['4795763_2518821']: THREE.Mesh
  }
  materials: {
    ['4795763_2518821']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Emblem-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['4795763_2518821'].geometry} material={materials['4795763_2518821']} position={[0, -0.001, 0]} />
    </group>
  )
}

useGLTF.preload('/models/Emblem-transformed.glb')
