/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Updated to use new Emblem.glb from /public/models/Emblem.glb
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFAction = THREE.AnimationClip

type GLTFResult = GLTF & {
  nodes: {
    ['4795763_2518821']: THREE.Mesh
  }
  materials: {
    ['4795763_2518821']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Emblem.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes['4795763_2518821'].geometry}
        material={materials['4795763_2518821']}
        position={[0, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/Emblem.glb')
