/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\AnimatedModels\Note_printer2.glb --transform --types --shadows --output src\components\shared-3d\models\NotePrinterAnimatedNew.tsx --keepnames 
Files: public\AnimatedModels\Note_printer2.glb [394.02MB] > D:\FREELANCING\MAGIC TEAL\JUImain\src\components\shared-3d\models\Note_printer2-transformed.glb [19.22MB] (95%)
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'
import { MotionValue } from 'framer-motion'

type ActionName = 'TopAction' | 'BottomAction'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Cylinder035: THREE.Mesh
    Cylinder035_1: THREE.Mesh
    Cylinder035_2: THREE.Mesh
    Cylinder038: THREE.Mesh
    Cylinder038_1: THREE.Mesh
  }
  materials: {
    Black_Metal: THREE.MeshPhysicalMaterial
    Neon: THREE.MeshStandardMaterial
    Logo: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function NotePrinterAnimated(props: React.JSX.IntrinsicElements['group'] & { progress?: MotionValue<number> }) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/AnimatedModels/Note_printer2-transformed.glb') as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)

  // Initialize animations but keep them paused
  useEffect(() => {
    Object.values(actions).forEach((action) => {
      if (action) {
        action.play().paused = true
      }
    })
  }, [actions])

  // Sync animation time with scroll progress
  useFrame(() => {
    if (props.progress) {
      const p = props.progress.get()
      
      const topAction = actions['TopAction']
      const bottomAction = actions['BottomAction']
      
      if (topAction) {
        const duration = topAction.getClip().duration
        topAction.time = (1 - p) * duration
      }
      
      if (bottomAction) {
        const duration = bottomAction.getClip().duration
        bottomAction.time = p * duration
      }
    }
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Top" position={[-0.255, 2.587, 0]} scale={1.514}>
          <group name="Cylinder036" position={[0.198, -0.02, -0.001]} scale={0.66}>
            <mesh name="Cylinder035" castShadow receiveShadow geometry={nodes.Cylinder035.geometry} material={materials.Black_Metal} />
            <mesh name="Cylinder035_1" castShadow receiveShadow geometry={nodes.Cylinder035_1.geometry}>
              <meshStandardMaterial
                {...materials.Neon}
                color="#00D1FF"
                emissive="#00D1FF"
                emissiveIntensity={10}
                toneMapped={false}
              />
            </mesh>
            <mesh name="Cylinder035_2" castShadow receiveShadow geometry={nodes.Cylinder035_2.geometry}>
              <meshStandardMaterial
                {...materials.Logo}
                color="#00D1FF"
                emissive="#00D1FF"
                emissiveIntensity={10}
                toneMapped={false}
                transparent
                opacity={1}
                polygonOffset
                polygonOffsetFactor={-1}
              />
            </mesh>
          </group>
        </group>
        <group name="Bottom" position={[-0.255, -0.542, 0]} scale={1.514}>
          <group name="Cylinder034" position={[-0.003, -0.004, 0]} scale={0.66}>
            <mesh name="Cylinder038" castShadow receiveShadow geometry={nodes.Cylinder038.geometry} material={materials.Black_Metal} />
            <mesh name="Cylinder038_1" castShadow receiveShadow geometry={nodes.Cylinder038_1.geometry}>
              <meshStandardMaterial
                {...materials.Neon}
                color="#00D1FF"
                emissive="#00D1FF"
                emissiveIntensity={10}
                toneMapped={false}
              />
            </mesh>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/AnimatedModels/Note_printer2-transformed.glb')
