/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\AnimatedModels\Note_printer2.glb --transform --types --shadows --output src\components\shared-3d\models\NotePrinterAnimatedNew.tsx --keepnames 
Files: public\AnimatedModels\Note_printer2.glb [394.02MB] > D:\FREELANCING\MAGIC TEAL\JUImain\src\components\shared-3d\models\Note_printer2-transformed.glb [19.22MB] (95%)
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations, Text } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'
import { MotionValue } from 'framer-motion'

type ActionName = 'TopAction' | 'BottomAction'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Cylinder035: THREE.Mesh
    Cylinder035_1: THREE.Mesh
    Cylinder035_2: THREE.Mesh
    Cylinder038: THREE.Mesh
    Cylinder038_1: THREE.Mesh
  }
  materials: {
    Black_Metal: THREE.MeshPhysicalMaterial
    Neon: THREE.MeshStandardMaterial
    Logo: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

const NUM_SEGMENTS = 16
const RADIUS = 1.478
const X_RIGHT = 0.22

interface SerialSegmentProps {
  index: number
  rotationRef: React.MutableRefObject<number>
}

function SerialSegment({ index, rotationRef }: SerialSegmentProps) {
  const textRef = useRef<any>(null)
  const materialRef = useRef<THREE.MeshStandardMaterial>(null)
  const lastSerialText = useRef<string>('')

  // Angle positioning for segment around the cylinder face
  const theta = (((NUM_SEGMENTS - index) % NUM_SEGMENTS + 0.12) * 2 * Math.PI) / NUM_SEGMENTS

  useFrame(() => {
    if (!textRef.current || !materialRef.current) return

    const rot = rotationRef.current
    const stepAngle = (2 * Math.PI) / NUM_SEGMENTS

    // How many segment steps the cylinder has rotated past this segment
    const stepProgress = rot / stepAngle
    const segmentOffset = stepProgress - index

    if (rot < 0.05 || segmentOffset < 0.02) {
      // Not yet reached print head or initial state before scroll — face is blank
      textRef.current.visible = false
    } else {
      textRef.current.visible = true
      const cycle = Math.floor(Math.max(0, segmentOffset) / NUM_SEGMENTS)
      const serialIndex = index + cycle * NUM_SEGMENTS
      const serialNum = `AA${12350 + serialIndex * 5}`

      if (lastSerialText.current !== serialNum) {
        lastSerialText.current = serialNum
        textRef.current.text = serialNum
      }

      // Flash pulse effect when the text is first stamped/printed at the print head
      const stepFraction = Math.max(0, segmentOffset) % 1.0
      if (stepFraction < 0.35) {
        const pulse = 1 - stepFraction / 0.35
        materialRef.current.emissiveIntensity = 10 + pulse * 25
      } else {
        materialRef.current.emissiveIntensity = 10
      }
    }
  })

  return (
    <group rotation={[theta, 0, 0]}>
      <Text
        ref={textRef}
        position={[X_RIGHT, RADIUS, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        fontSize={0.075}
        letterSpacing={0.15}
        anchorX="center"
        anchorY="middle"
        fontStyle="italic"
      >
        AA12350
        <meshStandardMaterial
          ref={materialRef}
          color="#00D1FF"
          emissive="#00D1FF"
          emissiveIntensity={10}
          toneMapped={false}
        />
      </Text>
    </group>
  )
}

function CylinderSerialNumbers({ rotationRef }: { rotationRef: React.MutableRefObject<number> }) {
  const segments = Array.from({ length: NUM_SEGMENTS }, (_, i) => i)

  return (
    <group name="CylinderSerialNumbers">
      {segments.map((i) => (
        <SerialSegment key={i} index={i} rotationRef={rotationRef} />
      ))}
    </group>
  )
}

export function NotePrinterAnimated(props: React.JSX.IntrinsicElements['group'] & { progress?: MotionValue<number>; isMobile?: boolean }) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/AnimatedModels/Note_printer2-transformed.glb') as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)

  // Stop GLTF clip actions to allow direct smooth rotation control
  useEffect(() => {
    Object.values(actions).forEach((action) => {
      if (action) {
        action.stop()
      }
    })
  }, [actions])

  const topCylinderRef = useRef<THREE.Group>(null)
  const bottomCylinderRef = useRef<THREE.Group>(null)
  const targetRotation = useRef(0)
  const currentRotation = useRef(0)
  const lastP = useRef<number | null>(null)

  // 60FPS smooth lerped rotation for both cylinders in the forward direction on scroll
  useFrame((_, delta) => {
    if (props.progress) {
      const p = props.progress.get()
      if (lastP.current !== null) {
        const dp = Math.abs(p - lastP.current)
        targetRotation.current += dp * 5
      }
      lastP.current = p
    }

    // Smooth lerp for graceful slow rotation without jitter
    currentRotation.current = THREE.MathUtils.lerp(
      currentRotation.current,
      targetRotation.current,
      Math.min(delta * 6, 1)
    )

    if (topCylinderRef.current) {
      topCylinderRef.current.rotation.x = -currentRotation.current
    }
    if (bottomCylinderRef.current) {
      bottomCylinderRef.current.rotation.x = currentRotation.current
    }
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Top" position={[-0.255, 2.587, 0]} scale={1.514}>
          <group ref={topCylinderRef} name="Cylinder036" position={[0.198, -0.02, -0.001]} scale={0.66}>
            <mesh name="Cylinder035" castShadow receiveShadow geometry={nodes.Cylinder035.geometry} material={materials.Black_Metal} />
            <mesh name="Cylinder035_1" castShadow receiveShadow geometry={nodes.Cylinder035_1.geometry}>
              <meshStandardMaterial
                {...materials.Neon}
                color="#00D1FF"
                emissive="#00D1FF"
                emissiveIntensity={10}
                toneMapped={false}
              />
            </mesh>
            <mesh name="Cylinder035_2" castShadow receiveShadow geometry={nodes.Cylinder035_2.geometry}>
              <meshStandardMaterial
                {...materials.Logo}
                color="#00D1FF"
                emissive="#00D1FF"
                emissiveIntensity={10}
                toneMapped={false}
                transparent
                opacity={1}
                polygonOffset
                polygonOffsetFactor={-1}
              />
            </mesh>
          </group>
        </group>
        <group name="Bottom" position={[-0.255, -0.542, 0]} scale={1.514}>
          <group ref={bottomCylinderRef} name="Cylinder034" position={[-0.003, -0.004, 0]} scale={0.66}>
            <mesh name="Cylinder038" castShadow receiveShadow geometry={nodes.Cylinder038.geometry} material={materials.Black_Metal} />
            <mesh name="Cylinder038_1" castShadow receiveShadow geometry={nodes.Cylinder038_1.geometry}>
              <meshStandardMaterial
                {...materials.Neon}
                color="#00D1FF"
                emissive="#00D1FF"
                emissiveIntensity={10}
                toneMapped={false}
              />
            </mesh>
            <CylinderSerialNumbers rotationRef={currentRotation} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/AnimatedModels/Note_printer2-transformed.glb')
