/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Paint_mixer.glb --transform --types --shadows --output src/components/shared-3d/models/PaintMixer.tsx 
Files: public/models/Paint_mixer.glb [1.66MB] > D:\FREELANCING\MAGIC TEAL\JUImain\src\components\shared-3d\models\Paint_mixer-transformed.glb [259.82KB] (84%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'Paint_mixerAction'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Cylinder001: THREE.Mesh
    Cylinder001_1: THREE.Mesh
  }
  materials: {
    Neon: THREE.MeshStandardMaterial
    Black: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

export function Model({ isMobile, ...props }: React.JSX.IntrinsicElements['group'] & { isMobile?: boolean }) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/models/Paint_mixer-transformed.glb') as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)

  React.useEffect(() => {
    if (actions && actions['Paint_mixerAction']) {
      actions['Paint_mixerAction'].play()
    }
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Paint_mixer">
          <mesh name="Cylinder001" castShadow receiveShadow geometry={nodes.Cylinder001.geometry} material={materials.Neon} />
          <mesh name="Cylinder001_1" castShadow receiveShadow geometry={nodes.Cylinder001_1.geometry} material={materials.Black} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Paint_mixer-transformed.glb')
